sudo: required
services:
  - docker

before_install:
  - docker build -t my_image -f Dockerfile.dev .

script:
  - docker run -e CI=true my_image npm run test

deploy:
  - provider:  elasticbeanstalk
    region: "us-east-1"
    app: "frontend"
    env: "Frontend-env"
    bucket_name:  "elasticbeanstalk-us-east-1-621146903815"
    bucket_path: "frontend"
    on:
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRETE_KEY"